# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: wecube_plugins_itsdangerous v0.2.1\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-02-24 10:45+0800\n"
"PO-Revision-Date: 2021-02-24 10:45+0800\n"
"Last-Translator: wecube <EMAIL@ADDRESS>\n"
"Language-Team: zh-CN <LL@li.org>\n"
"Language: zh-CN \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:92
msgid "failed to acquire lock, package cache may not be available"
msgstr "获取锁失败，包文件缓存可能无法正常使用"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Instance Ids"
msgstr "实例"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Line"
msgstr "行"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Content"
msgstr "内容"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "Message"
msgstr "消息"

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:390
#: ../wecube_plugins_itsdangerous/apps/processor/api.py:453
msgid "源文件"
msgstr ""

#: ../wecube_plugins_itsdangerous/apps/processor/api.py:544
#, python-format
msgid "missing query param: %(attribute)s, eg. /v1/api?%(attribute)s=value"
msgstr "缺少qeury参数: %(attribute)s, 例如 /v1/api?%(attribute)s=value"

#: ../wecube_plugins_itsdangerous/common/controller.py:44
#: ../wecube_plugins_itsdangerous/common/controller.py:62
#: ../wecube_plugins_itsdangerous/common/controller.py:91
msgid "data must be list type"
msgstr "data必须是列表([])类型"

#: ../wecube_plugins_itsdangerous/common/controller.py:124
msgid "data must be dict type"
msgstr "data必须是字典({})类型"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:30
msgid "Plugin Business Processing Error"
msgstr "插件业务处理错误"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:40
msgid "Field Missing"
msgstr "字段缺失"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:44
#, python-format
msgid "column: %(attribute)s must be specific"
msgstr "必须指定 %(attribute)s 列的值"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:54
msgid "Validation Error"
msgstr "校验错误"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:58
#, python-format
msgid "column %(attribute)s validate failed, because: %(msg)s"
msgstr "列 %(attribute)s 校验错误, 原因: %(msg)s"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:74
#, python-format
msgid "the resource(%(resource)s) you request not found"
msgstr "资源(%(resource)s) 不存在"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:84
msgid "Batch Operation Partial Error"
msgstr "批量操作错误"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:88
#, python-format
msgid "fail to %(action)s [%(num)s] record, detail error in the data block"
msgstr "[%(num)s] 个记录%(action)s失败, 详细信息请参见data内容"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:98
msgid "Conflict"
msgstr "冲突"

#: ../wecube_plugins_itsdangerous/common/exceptions.py:102
#, python-format
msgid "object[%(oid)s] is used by %(name)s"
msgstr "资源[%(oid)s] 被 %(name)s 使用"

#: ../wecube_plugins_itsdangerous/common/s3.py:32
msgid "invalid s3 endpoint url, eg: schema://host[:port]/bucket/object"
msgstr "非法的s3 url, 正确格式如: schema://host[:port]/bucket/object"

#: ../wecube_plugins_itsdangerous/common/s3.py:48
#, python-format
msgid "failed to download file[%(filepath)s] from s3: %(reason)s"
msgstr "从s3下载文件[%(filepath)s]失败， %(reason)s"

#: ../wecube_plugins_itsdangerous/common/utils.py:94
msgid "Connection Error"
msgstr "连接错误"

#: ../wecube_plugins_itsdangerous/common/utils.py:95
msgid "Failed to establish a new connection"
msgstr "无法建立连接"

#: ../wecube_plugins_itsdangerous/common/utils.py:101
msgid "Timeout Error"
msgstr "超时错误"

#: ../wecube_plugins_itsdangerous/common/utils.py:102
msgid "Server do not respond"
msgstr "服务器无响应"

#: ../wecube_plugins_itsdangerous/common/utils.py:111
msgid "Not Found"
msgstr "资源不存在"

#: ../wecube_plugins_itsdangerous/common/utils.py:112
msgid "The resource you request not exist"
msgstr "你请求的资源不存在"

#: ../wecube_plugins_itsdangerous/common/utils.py:126
msgid "Server Error"
msgstr "服务器错误"

#: ../wecube_plugins_itsdangerous/db/resource.py:23
#: ../wecube_plugins_itsdangerous/db/validator.py:33
#, python-format
msgid "reference of %(resource)s(%(id)s) not found"
msgstr "引用的资源 %(resource)s(%(id)s) 不存在"

#: ../wecube_plugins_itsdangerous/db/resource.py:230
#: ../wecube_plugins_itsdangerous/db/resource.py:236
#, python-format
msgid "%(value)s is not acceptable, use %(fixed_value)s instead"
msgstr "非法值：%(value)s, 请使用 %(fixed_value)s 之一"

#: ../wecube_plugins_itsdangerous/db/resource.py:449
msgid "specify at least one field content"
msgstr "至少指定一个字段：脚本字段 或 脚本地址"

#: ../wecube_plugins_itsdangerous/db/validator.py:17
#, python-format
msgid "expected string, not %(type)s "
msgstr "期望字符串类型，当前输入类型为 %(type)s"

#: ../wecube_plugins_itsdangerous/db/validator.py:20
#, python-format
msgid "length required: %(min)d <= %(value)d <= %(max)d"
msgstr "非法长度: %(min)d <= %(value)d <= %(max)d"

#: ../wecube_plugins_itsdangerous/db/validator.py:45
#, python-format
msgid "expected %(choices)s, not %(value)s"
msgstr "期望值为 %(choices)s，当前输入为 %(value)s"

#: ../wecube_plugins_itsdangerous/db/validator.py:48
#, python-format
msgid "value should be >= 1, not %(value)s"
msgstr "值应 >= 1, 当前值为 %(value)s"

#: ../wecube_plugins_itsdangerous/db/validator.py:50
#, python-format
msgid "expected string in %(choices)s or int(>=1), not %(type)s "
msgstr "期望值为 %(choices)s 或 >= 1的整数，当前输入为 %(type)s"

#: talos ValidationError
#, python-format
msgid "detail: column %(attribute)s validate failed, because: %(msg)s"
msgstr "列 %(attribute)s 校验不通过, 原因: %(msg)s"
